name: Node.js CI Student_MN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  building:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      # 1) Cài Node (KHÔNG cache Yarn ở đây)
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 2) Bật Corepack và kích hoạt đúng Yarn theo package.json
      - name: "Enable Corepack + use Yarn from package.json"
        shell: bash
        run: |
          corepack enable
          VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          corepack prepare "yarn@$VERSION" --activate
          yarn --version

      # 3) Cache Yarn (đường dẫn do Yarn trả về)
      - name: Get Yarn cache dir
        id: yarn-cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-${{ matrix.node-version }}-

      # 4) Cài deps, build, test
      - name: Install deps (Yarn Berry)
        run: yarn install --immutable

      - name: Lint (if script exists)
        shell: bash
        run: |
          if yarn -s run | grep -qE '^\s+lint\s'; then
            yarn lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Build (if script exists)
        shell: bash
        run: |
          if yarn -s run | grep -qE '^\s+build\s'; then
            yarn build
          else
            echo "No build script. Skipping."
          fi

      - name: Test (if script exists)
        shell: bash
        run: |
          if yarn -s run | grep -qE '^\s+test\s'; then
            yarn test --ci
          else
            echo "No test script. Skipping."
          fi
